export const socketEvents = {
    "CAB_BOOK":"CAB_BOOK",
    "NEW_RIDE_REQUEST":"NEW_RIDE_REQUEST",
    "CAB_BOOKED":"CAB_BOOKED",
    "SEARCH_CUSTOMER" :"SEARCH_CUSTOMER",
    // on validatione error
    "UNAUTHORIZED":"UNAUTHORIZED",
    "EV_DRIVER_LIVE_LOCATION":"EV_DRIVER_LIVE_LOCATION",
    "EV_DRIVER_LOGGED_OUT":"EV_DRIVER_LOGGED_OUT"

}



